const chList = [
  "TAYSON",
  "MIGUEL MATEUS",
  "FRIDA KHALO",
  "JOE ARROYO",
  "COCO CHANEL",
  "MICKEY MOUSE",
  "RUBÉN BLADES",
  "STEPHEN HAWKING",
  "DIOMEDES DIAZ 2",
  "NN",
  "N.A",
  "JASON STATHAM",
  "RICARDO ARJONA",
  "CARLOS CASTAÑO",
  "BEYONCE",
  "KANY GARCÍA",
  "BATMAN",
  "DIOMEDES DÍAZ 1",
  "HERENCIA DE TIMBIQUI",
  "RAFAEL ESCALONA",
  "MARIBEL MADRIGAL",
  "CELIA CRUZ",
  "GOKU",
  "BOOGALOO",
  "ANA GABRIEL",
  "MAFALDA",
  "LA CELOSA DE CHEPE FORTUNA",
  "SOFÍA VERGARA"
];
module.exports={
    chList
}